input {
    file {
        path => "/logs/app.log"
        start_position => "end"
    }
}

filter {
    json {
        source => "message"
    }

    date {
        match => [ "timestamp", "yyyy-MM-dd HH:mm:ss" ]
        target => "@timestamp"
    }
}

output {
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "app-academia-logs"
    }
    
    stdout {
        codec => rubydebug
    }
}