import React, { useEffect, useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import * as Linking from 'expo-linking';
import { StatusBar } from 'expo-status-bar';
import { SafeAreaProvider } from 'react-native-safe-area-context';
import { api, clearSession, getSessionEmail, hasSession, saveSession, setSessionExpiredHandler } from './src/api';
import { Button, Field, Logo, Notice } from './src/components';
import { colors } from './src/theme';

function Shell({ children, back, onBack }) {
  return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={s.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.scroll}><View style={s.top}>{back ? <Pressable onPress={onBack}><Text style={s.back}>‹ Voltar</Text></Pressable> : <Logo />}</View>{children}</ScrollView></KeyboardAvoidingView></SafeAreaView>;
}

function Login({ go, done, sessionNotice }) {
  const [email, setEmail] = useState(''); const [senha, setSenha] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const submit = async () => { if (!email.trim() || !senha) return setError('Preencha o e-mail e a senha.'); setBusy(true); setError(''); try { const cleanEmail = email.trim().toLowerCase(); const data = await api.login(cleanEmail, senha); await saveSession(data, cleanEmail); done(cleanEmail); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  return <Shell><Text style={s.eyebrow}>TREINOPRO</Text><Text style={s.title}>Seu trabalho,{String.fromCharCode(10)}mais organizado.</Text><Text style={s.subtitle}>Entre na sua conta de personal para gerenciar seus dados.</Text>{error ? <Notice type="error">{error}</Notice> : sessionNotice ? <Notice type="error">{sessionNotice}</Notice> : null}<Field label="E-mail" placeholder="voce@exemplo.com" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none"/><Field style={s.field} label="Senha" placeholder="Sua senha" value={senha} onChangeText={setSenha} secureTextEntry/><Pressable onPress={() => go('forgot')}><Text style={s.linkRight}>Esqueci minha senha</Text></Pressable><Button title="Entrar" loading={busy} onPress={submit} style={s.action}/><Button title="Criar minha conta" variant="secondary" onPress={() => go('register')} style={s.smallAction}/><Text style={s.terms}>Ao continuar, você concorda com o uso dos seus dados para autenticação.</Text></Shell>;
}

function Register({ go }) {
  const [form, setForm] = useState({ nome: '', telefone: '', email: '', senha: '', confirmar_senha: '' }); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const set = (key) => (value) => setForm((old) => ({ ...old, [key]: value }));
  const submit = async () => { if (Object.values(form).some((v) => !v.trim())) return setError('Preencha todos os campos.'); if (form.senha !== form.confirmar_senha) return setError('As senhas precisam ser iguais.'); setBusy(true); setError(''); try { const data = await api.register({ ...form, email: form.email.trim().toLowerCase() }); setMessage(data.message); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  if (message) return <Shell back onBack={() => go('login')}><View style={s.successIcon}><Text style={s.successMark}>✓</Text></View><Text style={s.titleSmall}>Confira seu e-mail</Text><Text style={s.subtitle}>{message}</Text>{error ? <Notice type="error">{error}</Notice> : null}<Button title="Voltar para o login" onPress={() => go('login')} style={s.action}/><Button title="Reenviar e-mail" variant="secondary" onPress={async () => { try { await api.resendConfirmation(form.email); } catch (e) { setError(e.message); } }} style={s.smallAction}/></Shell>;
  return <Shell back onBack={() => go('login')}><Text style={s.titleSmall}>Crie sua conta</Text><Text style={s.subtitle}>Comece configurando seus dados de acesso.</Text>{error ? <Notice type="error">{error}</Notice> : null}<Field label="Nome completo" value={form.nome} onChangeText={set('nome')} placeholder="Como devemos chamar você?"/><Field style={s.field} label="Telefone" value={form.telefone} onChangeText={set('telefone')} placeholder="(85) 99999-9999" keyboardType="phone-pad"/><Field style={s.field} label="E-mail" value={form.email} onChangeText={set('email')} placeholder="voce@exemplo.com" keyboardType="email-address" autoCapitalize="none"/><Field style={s.field} label="Senha" value={form.senha} onChangeText={set('senha')} placeholder="De 6 a 30 caracteres" secureTextEntry/><Field style={s.field} label="Confirmar senha" value={form.confirmar_senha} onChangeText={set('confirmar_senha')} secureTextEntry/><Button title="Criar conta" onPress={submit} loading={busy} style={s.action}/></Shell>;
}

function Forgot({ go }) {
  const [email, setEmail] = useState(''); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(null);
  const submit = async () => { if (!email.trim()) return setNotice({ error: true, text: 'Informe seu e-mail.' }); setBusy(true); try { const data = await api.forgotPassword(email.trim().toLowerCase()); setNotice({ text: data.message }); } catch (e) { setNotice({ error: true, text: e.message }); } finally { setBusy(false); } };
  return <Shell back onBack={() => go('login')}><Text style={s.titleSmall}>Recuperar senha</Text><Text style={s.subtitle}>Enviaremos um link para você criar uma nova senha.</Text>{notice ? <Notice type={notice.error ? 'error' : 'success'}>{notice.text}</Notice> : null}<Field label="E-mail" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" placeholder="voce@exemplo.com"/><Button title="Enviar link" loading={busy} onPress={submit} style={s.action}/></Shell>;
}

function Reset({ token, go }) {
  const [senha, setSenha] = useState(''); const [confirm, setConfirm] = useState(''); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(null);
  const submit = async () => { if (senha.length < 6 || senha !== confirm) return setNotice({ error: true, text: 'Use ao menos 6 caracteres e repita a mesma senha.' }); setBusy(true); try { const data = await api.resetPassword(token, senha, confirm); await clearSession(); setNotice({ text: data.message, done: true }); } catch (e) { setNotice({ error: true, text: e.message }); } finally { setBusy(false); } };
  return <Shell back onBack={() => go('login')}><Text style={s.titleSmall}>Nova senha</Text><Text style={s.subtitle}>Escolha uma senha diferente da atual.</Text>{notice ? <Notice type={notice.error ? 'error' : 'success'}>{notice.text}</Notice> : null}{notice?.done ? <Button title="Entrar novamente" onPress={() => go('login')}/> : <><Field label="Nova senha" value={senha} onChangeText={setSenha} secureTextEntry/><Field style={s.field} label="Confirmar senha" value={confirm} onChangeText={setConfirm} secureTextEntry/><Button title="Salvar nova senha" loading={busy} onPress={submit} style={s.action}/></>}</Shell>;
}

function Home({ email, go, logout }) {
  return <Shell><View style={s.homeHeader}><View><Text style={s.eyebrow}>ÁREA DO PERSONAL</Text><Text style={s.homeTitle}>Olá!</Text></View><View style={s.avatar}><Text style={s.avatarText}>{(email || 'P')[0].toUpperCase()}</Text></View></View><View style={s.hero}><Text style={s.heroLabel}>CONTA ATIVA</Text><Text style={s.heroTitle}>Tudo certo por aqui.</Text><Text style={s.heroText}>Sua conta está autenticada e pronta para usar os recursos disponíveis.</Text></View><Text style={s.sectionTitle}>Minha conta</Text><Pressable style={s.menuCard} onPress={() => go('profile')}><View><Text style={s.menuTitle}>Dados e segurança</Text><Text style={s.menuText}>Nome, senha e exclusão da conta</Text></View><Text style={s.chevron}>›</Text></Pressable><View style={s.coming}><Text style={s.comingTitle}>Próximos recursos</Text><Text style={s.comingText}>Alunos, agenda e notificações aparecerão aqui quando os respectivos endpoints estiverem disponíveis no backend.</Text></View><Button title="Sair da conta" variant="secondary" onPress={logout} style={s.action}/></Shell>;
}

function Profile({ email, go, logout }) {
  const [nome, setNome] = useState(''); const [senha, setSenha] = useState(''); const [confirm, setConfirm] = useState(''); const [busy, setBusy] = useState(''); const [notice, setNotice] = useState(null);
  const run = async (kind, fn) => { setBusy(kind); setNotice(null); try { const data = await fn(); setNotice({ text: data.message }); } catch (e) { setNotice({ error: true, text: e.message }); } finally { setBusy(''); } };
  return <Shell back onBack={() => go('home')}><Text style={s.titleSmall}>Dados e segurança</Text><Text style={s.subtitle}>{email || 'Sua conta de personal'}</Text>{notice ? <Notice type={notice.error ? 'error' : 'success'}>{notice.text}</Notice> : null}<View style={s.card}><Text style={s.cardTitle}>Alterar nome</Text><Field label="Novo nome" value={nome} onChangeText={setNome} placeholder="Seu novo nome"/><Button title="Salvar nome" loading={busy === 'name'} onPress={() => nome.trim() ? run('name', () => api.changeName(nome.trim())) : setNotice({ error: true, text: 'Informe o novo nome.' })} style={s.smallAction}/></View><View style={s.card}><Text style={s.cardTitle}>Alterar senha</Text><Text style={s.cardText}>Enviaremos o link de alteração para o e-mail da sua conta.</Text><Button title="Enviar link por e-mail" variant="secondary" loading={busy === 'password'} onPress={() => run('password', () => api.requestPasswordChange(email))}/></View><View style={[s.card, s.dangerCard]}><Text style={[s.cardTitle, s.dangerText]}>Excluir conta</Text><Text style={s.cardText}>A exclusão só será concluída pelo link enviado ao seu e-mail.</Text><Field label="Senha" value={senha} onChangeText={setSenha} secureTextEntry/><Field style={s.field} label="Confirmar senha" value={confirm} onChangeText={setConfirm} secureTextEntry/><Button title="Solicitar exclusão" variant="danger" loading={busy === 'delete'} onPress={() => run('delete', () => api.deleteAccount(senha, confirm))} style={s.smallAction}/><Pressable onPress={() => run('resend', api.resendDeleteEmail)}><Text style={s.linkCenter}>Reenviar e-mail de exclusão</Text></Pressable></View><Button title="Sair da conta" variant="secondary" onPress={logout}/></Shell>;
}

function Main() {
  const [screen, setScreen] = useState('loading'); const [email, setEmail] = useState(''); const [token, setToken] = useState(''); const [sessionNotice, setSessionNotice] = useState('');
  useEffect(() => { setSessionExpiredHandler(() => { setEmail(''); setSessionNotice('Sua sessão expirou. Entre novamente.'); setScreen('login'); }); Promise.all([hasSession(), getSessionEmail()]).then(([ok, storedEmail]) => { setEmail(storedEmail); setScreen(ok ? 'home' : 'login'); }); const handle = ({ url }) => { const parsed = Linking.parse(url); const value = parsed.queryParams?.token; if (value && (parsed.path || '').includes('senha')) { setToken(String(value)); setScreen('reset'); } }; Linking.getInitialURL().then((url) => url && handle({ url })); const sub = Linking.addEventListener('url', handle); return () => { sub.remove(); setSessionExpiredHandler(null); }; }, []);
  const logout = async () => { await clearSession(); setEmail(''); setSessionNotice(''); setScreen('login'); };
  if (screen === 'loading') return <SafeAreaView style={[s.safe, s.center]}><Logo /></SafeAreaView>;
  if (screen === 'login') return <Login go={setScreen} sessionNotice={sessionNotice} done={(value) => { setEmail(value); setSessionNotice(''); setScreen('home'); }}/>;
  if (screen === 'register') return <Register go={setScreen}/>;
  if (screen === 'forgot') return <Forgot go={setScreen}/>;
  if (screen === 'reset') return <Reset token={token} go={setScreen}/>;
  if (screen === 'profile') return <Profile email={email} go={setScreen} logout={logout}/>;
  return <Home email={email} go={setScreen} logout={logout}/>;
}

export default function App() { return <SafeAreaProvider><StatusBar style="dark"/><Main/></SafeAreaProvider>; }

const s = StyleSheet.create({
  flex: { flex: 1 }, safe: { flex: 1, backgroundColor: colors.background }, center: { alignItems: 'center', justifyContent: 'center' }, scroll: { flexGrow: 1, padding: 24, paddingBottom: 48, width: '100%', maxWidth: 560, alignSelf: 'center' }, top: { minHeight: 72, justifyContent: 'center' }, back: { fontWeight: '700', color: colors.ink, fontSize: 16 },
  eyebrow: { color: colors.primaryDark, fontWeight: '900', letterSpacing: 1.4, fontSize: 12, marginBottom: 10 }, title: { fontSize: 38, lineHeight: 43, fontWeight: '900', color: colors.ink, letterSpacing: -1.3, marginBottom: 14 }, titleSmall: { fontSize: 30, fontWeight: '900', color: colors.ink, marginBottom: 10 }, subtitle: { color: colors.muted, fontSize: 16, lineHeight: 24, marginBottom: 28 }, field: { marginTop: 16 }, linkRight: { color: colors.ink, fontWeight: '700', textAlign: 'right', marginTop: 12 }, linkCenter: { color: colors.danger, fontWeight: '700', textAlign: 'center', marginTop: 16 }, action: { marginTop: 24 }, smallAction: { marginTop: 12 }, terms: { textAlign: 'center', color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 22 },
  successIcon: { width: 72, height: 72, borderRadius: 36, backgroundColor: colors.successSoft, alignItems: 'center', justifyContent: 'center', marginBottom: 24 }, successMark: { color: colors.success, fontSize: 36, fontWeight: '900' }, homeHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 22 }, homeTitle: { color: colors.ink, fontSize: 32, fontWeight: '900' }, avatar: { width: 48, height: 48, borderRadius: 24, backgroundColor: colors.ink, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.primary, fontSize: 20, fontWeight: '900' },
  hero: { backgroundColor: colors.ink, borderRadius: 24, padding: 24, marginBottom: 28 }, heroLabel: { color: colors.primary, fontSize: 11, letterSpacing: 1.2, fontWeight: '900', marginBottom: 14 }, heroTitle: { color: '#FFF', fontWeight: '900', fontSize: 25, marginBottom: 8 }, heroText: { color: '#C2CAC6', fontSize: 15, lineHeight: 22 }, sectionTitle: { fontSize: 19, color: colors.ink, fontWeight: '900', marginBottom: 12 }, menuCard: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: colors.surface, padding: 18, borderRadius: 16, borderColor: colors.line, borderWidth: 1 }, menuTitle: { fontWeight: '800', fontSize: 16, color: colors.ink }, menuText: { color: colors.muted, marginTop: 5 }, chevron: { color: colors.muted, fontSize: 32 }, coming: { padding: 18, borderRadius: 16, backgroundColor: '#E9ECE8', marginTop: 14 }, comingTitle: { color: colors.ink, fontWeight: '800', marginBottom: 7 }, comingText: { color: colors.muted, lineHeight: 20 },
  card: { backgroundColor: colors.surface, borderColor: colors.line, borderWidth: 1, borderRadius: 18, padding: 18, marginBottom: 16 }, dangerCard: { borderColor: '#F0CACA' }, cardTitle: { fontSize: 18, fontWeight: '900', color: colors.ink, marginBottom: 12 }, cardText: { color: colors.muted, lineHeight: 20, marginBottom: 16 }, dangerText: { color: colors.danger },
});
