"""adiciona telefone_verificado no aluno

Revision ID: 31b222254f1b
Revises: 81e4013d5358
Create Date: 2026-09-20 12:51:22.610467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '31b222254f1b'
down_revision: Union[str, Sequence[str], None] = '81e4013d5358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alunos', sa.Column('telefone_verificado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alunos', 'telefone_verificado')
    # ### end Alembic commands ###
