"""adiciona solicitacoes de reagendamento

Revision ID: 63bdbc5db11f
Revises: 
Create Date: 2026-09-10 15:55:52.472460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '63bdbc5db11f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('usuario_ativo', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('email_verificado', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('agendamentos_fixos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_da_semana', sa.Enum('segunda', 'terca', 'quarta', 'quinta', 'sexta', 'sabado', 'domingo', name='dia_da_semana_enum'), nullable=False),
    sa.Column('horario_inicio', sa.Time(), nullable=False),
    sa.Column('horario_fim', sa.Time(), nullable=False),
    sa.Column('personal_id', sa.Integer(), nullable=False),
    sa.Column('capacidade_max', sa.Integer(), nullable=False),
    sa.CheckConstraint('capacidade_max > 0', name='ck_capacidade_max'),
    sa.CheckConstraint('horario_fim > horario_inicio', name='ck_agendamento_fixo_horarios'),
    sa.ForeignKeyConstraint(['personal_id'], ['personal.id'], name='fk_agendamentos_fixos_personal'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personal_id', 'dia_da_semana', 'horario_inicio', name='uq_aula_fixa_personal_dia_horario')
    )
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100, collation='utf8mb4_0900_ai_ci'), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('personal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personal_id'], ['personal.id'], name='fk_personal_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personal_id', 'nome', name='uq_alunos_personal_nome'),
    sa.UniqueConstraint('personal_id', 'telefone', name='uq_alunos_personal_telefone')
    )
    op.create_index('idx_telefone', 'alunos', ['telefone'], unique=False)
    op.create_table('alunos_participantes_da_aula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aula_fixa_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], name='fk_aluno_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['aula_fixa_id'], ['agendamentos_fixos.id'], name='fk_aula_fixa_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aula_fixa_id', 'aluno_id', name='uq_aula_fixa_aluno')
    )
    op.create_table('solicitacoes_mudanca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personal_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('aula_fixa_id', sa.Integer(), nullable=False),
    sa.Column('data_hora_aula_original', sa.DateTime(), nullable=False),
    sa.Column('nova_data_hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('nova_data_hora_fim', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'aceita', 'recusada', 'cancelada', 'expirada', name='statussolicitacao'), server_default=sa.text("'pendente'"), nullable=False),
    sa.Column('mensagem_externa_id', sa.String(length=150), nullable=True),
    sa.Column('motivo', sa.String(length=250), nullable=True),
    sa.Column('criada_em', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('respondida_em', sa.DateTime(), nullable=True),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.CheckConstraint('false', name='ck_solicitacao_fim_apos_inicio'),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], name='fk_solicitacao_aluno', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['aula_fixa_id'], ['agendamentos_fixos.id'], name='fk_solicitacao_aula_fixa', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['personal_id'], ['personal.id'], name='fk_solicitacao_personal', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mensagem_externa_id', name='uq_solicitacao_mensagem_externa')
    )
    op.create_index('ix_solicitacao_expira_em', 'solicitacoes_mudanca', ['expira_em'], unique=False)
    op.create_index('ix_solicitacao_personal_status', 'solicitacoes_mudanca', ['personal_id', 'status'], unique=False)
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personal_id', sa.Integer(), nullable=False),
    sa.Column('solicitacao_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('mensagem', sa.String(length=500), nullable=False),
    sa.Column('lida', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('criada_em', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['personal_id'], ['personal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes_mudanca.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacoes_personal_id'), 'notificacoes', ['personal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notificacoes_personal_id'), table_name='notificacoes')
    op.drop_table('notificacoes')
    op.drop_index('ix_solicitacao_personal_status', table_name='solicitacoes_mudanca')
    op.drop_index('ix_solicitacao_expira_em', table_name='solicitacoes_mudanca')
    op.drop_table('solicitacoes_mudanca')
    op.drop_table('alunos_participantes_da_aula')
    op.drop_index('idx_telefone', table_name='alunos')
    op.drop_table('alunos')
    op.drop_table('agendamentos_fixos')
    op.drop_table('personal')
    # ### end Alembic commands ###
