"""remove telefone do personal

Revision ID: 81e4013d5358
Revises: 89b5ce041a72
Create Date: 2026-09-20 12:33:15.396989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = '81e4013d5358'
down_revision: Union[str, Sequence[str], None] = '89b5ce041a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('telefone'), table_name='personal')
    op.drop_column('personal', 'telefone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal', sa.Column('telefone', mysql.VARCHAR(length=15), nullable=False))
    op.create_index(op.f('telefone'), 'personal', ['telefone'], unique=True)
    # ### end Alembic commands ###
