"""adiciona push_token

Revision ID: c72f1d68435a
Revises: 3da83f808a73
Create Date: 2026-09-12 19:25:41.963617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'c72f1d68435a'
down_revision: Union[str, Sequence[str], None] = '3da83f808a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal', sa.Column('push_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal', 'push_token')
    # ### end Alembic commands ###
